### ISSUE TITLE
Implied multiplication is not recognised

### ISSUE THREAD

**Issue by helsmore** [equation-cloud/ecca#18]
Equations such as 'y=2x' do not parse correctly - output for example given is 'y = 2' for version 0.4.6

**Comment by rtb21** [comment]
It's fairly simple to allow 2x to parse correctly (and I'll implement it), however what starts to become more tricky is to work out how to deal with implicit multiplication followed by a power, for example 2x^5 is fairly clear what it means, however if the attmpeted implicit multiplication was 2[*]2^5 then it would need to be written as 22^5 which is clearly wrong. However the way the parser is set up I think this would significantly increase the number of rules required.

**Comment by helsmore** [comment]
It doesn't seem unreasonable to say that one of the operands of the implicit multiplication has to be a variable not a number.
